name: deploy
on:
  push:
    branches:
      - master
      - developer
      - feat-pipeline
  workflow_dispatch:

  
jobs:
  build:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Environment
        run: |
          echo "${{ secrets.DATABASE_HOSTNAME }}" > .env
          echo "${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "${{ secrets.DATABASE_PORT }}" >> .env
          echo "${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "${{ secrets.JWT_SECRET_KEY }}" >> .env
          cat .env
        shell: bash
      - name: Build docker
        env:
          IMAGE: bad:v1
          STORAGE_PATH: /prog/web_dad/storage/userimages
          CONTAINER_NAME: bad-app
        run: |
          docker build --cache-from $IMAGE -t $IMAGE .
          docker run -d -p 3001:3001 --name $CONTAINER_NAME -v $STORAGE_PATH:/app/public/userimages $IMAGE
