name: deploy
on:
  push:
    branches:
      - master
      - developer
      - feat-pipeline
  workflow_dispatch:

  
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Environment
        run: |
          echo "${{ secrets.DATABASE_HOSTNAME }}\n" > .env
          echo "${{ secrets.DATABASE_PASSWORD }}\n" >> .env
          echo "${{ secrets.DATABASE_PORT }}\n" >> .env
          echo "${{ secrets.DATABASE_USERNAME }}\n" >> .env
          echo "${{ secrets.JWT_SECRET_KEY }}\n" >> .env
          cat .env
        shell: bash
      - name: Build docker
        env:
          IMAGE: bad:v1
          STORAGE_PATH: /prog/web_dad/storage/userimages
        run: |
          docker build --cache-from $IMAGE -t $IMAGE .
          docker run -d -p 3001:3001 -v $STORAGE_PATH:/app/public/userimages $IMAGE
